global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#valeriy_mandarov'
