---
- name: Install app
  hosts: all
  become: true
  tags:
    - deploy_app

  tasks:

    - name: application container
      docker_container:
        name: reddit
        image: valmanmsk/otus-reddit:1.0
        ports:
        - "9292:9292"

